- name: data types
  hosts: local
  connection: local
  become: yes

  vars:
    COURSE: DevSecOps with AWS # string 
    DURATION: 120 # number
    is_live: true # boolean
    # list
    tools: #["linux","shell-script","ansible"]
    - linux
    - shell-script
    - ansible
    concepts: # dictionary or map
    - cloud: AWS
    - cm: ansible

  tasks:
  - name: print data types
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }} , is_live {{ is_live }} , tolls are {{ tools }} , concepts are {{ concepts }}"

# list: []
# ditionary or map: {}
