- name: user creation
  hosts: local
  connection: local
  become: yes

  tasks:
  - name: check user exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  # print the output
  - name: print the output
    ansible.builtin.debug: 
      msg: "{{ user_output }}"

  # create roboshop user
  - name: create roboshop user
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0