- name: nginx install and start
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
      
  - name: start nginx and enable
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes